%\SweaveUTF8
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
%
%  CHAPTER:The underlying models
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\chapter{The underlying model}
\label{cha:underlying}
  


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SECTION: Overview
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Overview}
\label{sec:underlying:overview}

This chapter highlights one specific model used to model the motion that a stock price time serie would follow. It is the one used in the Black--Scholes--Merton model, \citet{hull}.

Following \citet{shreve}, The \cref{eq:underlying:geometric:closed}, called a geometric Brownian motion, features a stochastic process where the only random component is the Brownian motion $\Bm$. Whilst the others parameters, $\alpha$ and $\sigma$, stand respectively for the annualized expected return and volatility of the theoretical stock price process, \citet{hull}.

\begin{center}
  \begin{equation}
    \Scontinuous
    \label{eq:underlying:geometric:closed}
  \end{equation}
\end{center}
 
In order to match with the constraints introduced by the Black and Scholes' pricing formula (\cref{sec:bsm:assumption}), the value the stock price may achieve at the end of a given period, according to constant mean rate of return and volatility, should be random and log--normally distributed (\citet{bs}).

Furthermore, the path following by any walks of the stock price motion should be  a continuous process, as the time frame decrease $\Dt \to 0$.
Therefore in addition to develop the model, all the aforementioned characteristics are shown to be true within this chapter.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SECTION: Derivation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Derivation}
\label{sec:underlying:derivation}

In order to get the differential form of equation \ref{eq:underlying:geometric:closed}, the Itô's formula (\cref{sec:upstream:ito}) is used. By applying the tranformation incurred by Itô, the \cref{eq:underlying:geometric:diff,eq:underlying:geometric:rate,eq:underlying:geometric:diff} emerge:
 
\begin{center}
  \begin{subequations}
    \begin{align}
      \Scontinousdiff \label{eq:underlying:geometric:diff} \\
      \Scontinuousrate \label{eq:underlying:geometric:rate}
    \end{align}
  \end{subequations}
\end{center}

The \cref{eq:underlying:geometric:closed} shows that any change occuring in the stock price $S$ over a small amount of time is due to the deterministic expected drift rate ($\alpha \St$) along with some amounts of added noise included by the random part ($\sigma d\Bm$). The \cref{eq:underlying:geometric:closed} denotes the stock return stochastic process, \citet{hull}.

\begin{align}
  d\ln{\St} &= (\alpha - \frac{\sigma ^2}{2}) dt 
              + \sigma d\Bm \label{eq:underlying:logreturn:diff} \\
  \ln{\frac{\St}{S(0)}} &= (\alpha - \frac{\sigma ^2}{2}) t 
              + \sigma \Bm \label{eq:underlying:log:return}
\end{align}

The \cref{eq:underlying:logreturn} exibits the natual logarithm of the stock price return occuring all over the period $t$. In other words, the expectation of this process, given by $(\alpha - \frac{\sigma ^2}{2}) \times t$ happens to be the expected value of the continously compounded rate of return for the aformentioned period of time, \citet{hull}.


\begin{figure}[h]
\centering
\input{figures/ItoAccuracy.tex}
\caption{Accuracy of Itô approximation}
\floatfoot{
  The above processes have been constructed over four distinctive groups of two "equivalent" geometric Brownian motions, following \cref{eq:underlying:geometric:closed,eq:underlying:geometric:diff}, respectively for the red and blue coloured path. 
The only parameters that change over the group are the couples $(dt, \sigma)$ which are set to $QA \equiv (360, 0.2)$, $QB \equiv (4, 0.2)$, $QC \equiv (360, 1)$ and $QD \equiv (4, 1)$. 
All the processes cover a period of four years and begin with initial value set to $50$.
}
\label{p:itoaccuracy}
\end{figure}

The approximation of the stochastic process \ref{eq:Scontinuous} achieved using the Itô's lemma depends exclusively on two factors; the volatility parameter $\sigma$ and the time period occuring between two measures $dt$. 
As shown throughout the \cref{p:itoaccuracy}, the less the volatility or time step, the better the approximation.
It is therefore key, during an analysis process to choose an appropriate time step according to a given volatility in order to provide accurate retults.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SUBSECTION: Distribution of the stock price process
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\subsection{Distribution of the stock price process}
\label{sub:Distribution of the stock price process}

The distributions here developed concern the \cref{eq:Scontinuous,eq:Scontinuousdiffrate,eq:underlyinglogreturn}. They are described using the first two moments, namely the expectation and variance.

The first distribution (\ref{eq:scontinuousdist}) is related to \cref{eq:Scontinuousdiffrate}. What is learnt from it, is that the process followed by \cref{eq:Scontinuous} has normally distributed returns with expected value and variance relying on the time period $dt$, \citet{shreve}.

\begin{center}
\begin{equation}
\dSr \sim N(\alpha dt, \sigma^2 dt)
\label{eq:scontinuousdist}
\end{equation}
\end{center}  
According to the (\cref{p:returndensity}), the normality qualification from equation \ref{eq:scontinuousdist} holds.

 
\begin{figure}[!h]
\centering
\input{figures/stock_return_density.tex}
\caption{Daily Basis Stock Return Density}
\label{p:returndensity}
\floatfoot{
The above density function has been constructed over 10000 samples of a unique process. The samples has been constructed following \cref{eq:Scontinuousdiffrate}. The arguments are set with the following value, $\alpha = 0$, $\sigma = 30\%$. The black density belongs to the normal bell curve with mean $\alpha$ and standard deviation of $\sigma \times \sqrt{dt}$. The period between each measure, namely $dt$ has been set to $10000^{-1}$. 
}
\end{figure}


%%%%%%%%%%%%%%%%%%%%%%%%%
%  Log-return
%%%%%%%%%%%%%%%%%%%%%%%%%

According to \cref{eq:underlyinglogreturn}, The distribution of the natural logarithm of the stock price return recorded over a time period of $t$ is characterized by \cref{eq:logreturndist}

\begin{center}
\begin{equation}
\ln{\frac{\St}{S\left(0\right)}} 
  \sim N((\alpha - \frac{\sigma^2}{2}) t, \sigma^2 t)
\label{eq:logreturndist}
\end{equation}
\end{center}  

\begin{figure}[!h]
\centering
\input{figures/stock_logreturn_density.tex}
\caption{Daily Basis Stock Return Density}
\label{p:logreturndensity}
\floatfoot{
The above density function has been constructed over three distinctive groups of 10000 samples eachs. All samples have been constructed following \cref{eq:underlyinglogreturn}. The arguments are set with the following value, $\alpha = 0$, $\sigma = 30\%$. The black density belongs to the normal bell curve with mean $(\alpha - \frac{\sigma^2}{2}) \times t$ and standard deviation of $\sigma \times \sqrt{dt}$. The time frame is one year ($t = 1$) and period between each measure, namely $dt$ has been set to $500^{-1}$. 
}
\end{figure}

From \cref{eq:underlyinglogreturn}, it could also be shown, by setting $X = \ln{\St}$ and $Y = \St$, that the randomly simulated stock price outcomes' distribution, following \cref{eq:Scontinuous}, match with the log--normal law [REF].
The above point directly echoes the upstream ideal conditions set by \citet{bs} , especially the one relating the stock price process.

The following equations shows the relation between the distribution of the log--return and the stock process itself. Let
\begin{align}
  X &= \ln{\St} \sim N\left(\mu \equiv \ln{S(0)} + \left(\alpha - \frac{\sigma^2}{2}\right) t, \delta^2 \equiv \sigma^2 t\right)
  \intertext{and}
  Y &= \St
  \intertext{
  By the existing relation between the log--normal law with respect to the normal law, the following relations emerges.
  }
  \mathop{\mathbb{E}} Y &= e^{\ln{S(0) + (\alpha - \frac{\sigma^2}{2}) t + \frac{\sigma ^2 t}{2}}} \\
  &= S(0) e^{\alpha t}
  \intertext{
  and
  }
  var(Y) &= (e^{\sigma^2 t} - 1) * e^{2 \mu * \delta^2} \\
  &= S(0)^2 e^{2 \alpha t} (e^{\sigma^2 t} - 1)
  \intertext{
  Consequently the stock price random variable $\St$ as relation [REF] for distribution.
  }
  \St \sim lognormal(\mu, \delta^2)
\end{align}

\begin{align}
\ln{\frac{\St}{S\left(0\right)}}  \sim N((\alpha - \frac{\sigma^2}{2}) t, \sigma^2 t)
\label{eq:logdist}
\end{align}

The \cref{p:logreturndensty,p:logdensity} refers respectively to distributions (\ref{eq:logreturndist}) and (\ref{eq:logdist}).

\begin{figure}[!h]
\centering 
\input{figures/stock_log_density.tex}
\caption{Daily Basis Stock Return Density}
\label{p:logdensity}
\floatfoot{
The above density function has been constructed over three distinctive groups of 10000 samples eachs. All samples have been constructed following \cref{eq:Scontinuous}. The arguments are set with the following value, $\alpha = 0$, $\sigma = 30\%$. The black density belongs to the log--normal curve with mean and standard deviation such as described in [REF]. The time frame is one year ($t = 1$) and period between each measure, namely $dt$ has been set to $500^{-1}$. 
}
\end{figure}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SUBSECTION: Flaws
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Flaws}
\label{sec:Flaws}

Even if the \cref{eq:Scontinuous} is used to model the stock price process, it exists some lacks with the observed real processes. The analysis ([CHA REF]) mainly covers the following discrepancy of the model against empirical results.
  
The volatility appearing in the aformentioned underlying model (\ref{eq:Scontinuous}) is constant as time passes.
Even if this consideration can be considered as true for short period of time, it is not the case over the long--run \citet{teneng2011limitations}.
Other model substitutes the process defined throughout this chapter with other ones including stochastic volatility processes, making it changing over time.
For this purpose, the Heston's model is developed in this current master thesis, which encompasses two stochastic processes, a geometric Brownian motion [???? + REF] for the stock price diffusion model [DIFUSION??] and a mean-reverting CIR model to compute the volatility as a stochastic process.
This model is exposed in \cref{sec:Heston}.

Following [REF and REF], the uderlying log--returns distribution is characterized by the normal law. Consequently, the random variable $\St$, at the fixed time $t$, is normal. 
However, according to empirical results, the random variable $d\St$ do not fit with the normal bell curve (\citet{clark1973}).
Therefore if the price changes are not normally distribution neither is the log--return and thus $\St$, at a fixed time $t$, is not log--normally distributed.
Along with the Heston model, another one is considerd; the Merton's jump--diffusion model. Both are able to modify the skewness and kurtosis of the log--return distibution curve. The Merton framework is developed in \cref{sec:MixedJump}. 