\section{Moments}

\section{The Brownian motion}
\subsection{Construction}
\subsection{Characterization of a Brownian motion by its moments}
\subsection{Quadratic variation}
Explain why Itô's lemma


\section{Itô's lemma}
\subsection{Problem solving formula}
Explain how useful the formula is in this context.
Show the relation between the formula and the tailor approximation.
\subsection{Itô's formula for Brownian motion}
\subsection{Properties}
quadratic variation, ...

\section{GARCH model: Expecting volatility}
\subsection{Empirical ,theoretical, and implied volatility}
\subsection{model}

fdsajklfhdjfhjdfhdlhfdjdsah
fdsajklfhdjfhjdfhdlhfdjdsah
fdsajklfhdjfhjdfhdlhfdjdsah
fdsajklfhdjfhjdfhdlhfdjdsah
fdsajklfhdjfhjdfhdlhfdjdsah
fdsajklfhdjfhjdfhdlhfdjdsah
fdsajklfhdjfhjdfhdlhfdjdsah
fdsajklfhdjfhjdfhdlhfdjdsah
fdsajklfhdjfhjdfhdlhfdjdsah

\section{A stochastic stock price evolution}
\subsection{overview}
matrix with variable -> continuous / discrete
% 
\subsection{Abstract model with continuous time component}
Construction throught ITO
\subsection{Abstract model with discrete time component}
why so useful + compare it with ito ?

\subsection{Parameters}
mu, sd, ... moments (lognormal)

\subsection{Definition of the mean and volatility}
Garch model for volatility

\section{Black-Scholes-Merton equation}
\subsection{Philosophy}
\subsection{Assumptions}
\subsection{The greeks}
\subsection{The model}
\subsection{Hedgind strategy with the greeks and the model}

\section{Volatility smiles}

\section{Alternatives to Black-Scholes-Merton}