\documentclass{beamer}
 
\usetheme{default}
\usepackage[latin1]{inputenc}
\usefonttheme{professionalfonts}
\usepackage{times}
\usepackage{pgf,tikz}
\usepackage{amsmath}
\usepackage{verbatim}
\usetikzlibrary{arrows,shapes}
\usepackage{ulem}
\usepackage{longtable}
\usepackage{tabularx}
\usepackage{adjustbox}
\usepackage{multirow}
\usepackage{float}
\usepackage{arydshln}
\usepackage{mathrsfs}




%%% Color
\definecolor{myred}{cmyk}{0, 0.7808, 0.4429, 0.1412}

 
% \usepackage[utf8]{inputenc}
\SweaveInput{../preamble/formula.Rnw}
\SweaveInput{../preamble/snippet.Rnw}
 
% \usetheme{Boadilla}
% \usecolortheme{default}




%Information to be included in the title page:
\title{Hedging performances of the Black-Scholes model in imperfect log-normal world}
\author{Anthony Tedde}
\institute{Louvain School of Management (LSM)}
\date{2018}
 
 
 
\begin{document}
\SweaveOpts{concordance=TRUE}
 
%---Table of content---------------------------------------------------------
\frame{\titlepage}
\section[]{}
\begin{frame}{Contents}
  \tableofcontents
\end{frame}
%---Fim do Sumário------------------------------------------------------------





% =============================================================================
% CONTEXT
% =============================================================================
\SweaveInput{context}

% =============================================================================
% Other Models
% =============================================================================
\SweaveInput{model}


% =============================================================================
% Methodology
% =============================================================================
\SweaveInput{methodology}

% =============================================================================
% Analysis and results
% =============================================================================
\SweaveInput{analysis}


% =============================================================================
% Conclusion
% =============================================================================
\begin{frame}{Conclusion}
  % \subsection{\BSM assumptions}
  
  \begin{itemize}
    \item Possibility to reproduce volatility smiles
    \item Better performances for in/at-the-money
    \item Effects of Gamma / Theta not negligible for out-of-the-money
    \item Usage of deltas Heston / Merton if possible
  \end{itemize} 

  \begin{block}{How to go further}
  \begin{itemize}
    \item Consider a wider range of assets
    \item Accurately measure the effect of Gamma / Theta
  \end{itemize} 
  \end{block}
  
\end{frame}



 
\end{document}