\section{Other models}


% ----------------------------------------------------------------------------- 
\begin{frame}{Other models}

\tableofcontents[currentsection]
 
\end{frame}
% -----------------------------------------------------------------------------





\subsection{Merton's Jump-Diffusion Model}
% ----------------------------------------------------------------------------- 
\begin{frame}{The Merton's Jump-Diffusion Model (MJD)}

\begin{block}{MJD stochastic process}
  \begin{align}
  \St &= S\left(0\right) e^{\left(\alpha - \frac{\sigma^2}{2} - \lambda \kappa\right) t + \sigma \Bm + \sum_{i=1}^{N_t} Y_i}
  \notag
\end{align}
  
\end{block}


\begin{block}{Graphical representation}
  \begin{figure}[ht]
  \centering
  \input{../figures/merton.path2.tex} 
\end{figure}
  
\end{block}
 
\end{frame}
% -----------------------------------------------------------------------------


% -----------------------------------------------------------------------------
\begin{frame}{MJD: log-return density}

\begin{block}{Impact on the skewness ($\mu$)}
\begin{figure}[h]
\centering
\input{../figures/MertonJumpReturn2.tex}
\end{figure}
\end{block}
\end{frame}

\begin{frame}{MJD: log-return density}
\begin{block}{Impact on the kurtosis ($\lambda$)}
\begin{figure}[h]
\centering
\input{../figures/MertonJumpReturnTails2.tex}
\end{figure}
\end{block}
 
\end{frame}
% -----------------------------------------------------------------------------




















\subsection{Heston stochastic volatility model}
% ----------------------------------------------------------------------------- 
\begin{frame}{The Heston stochastic volatility model (HSV)}

\begin{block}{HSV stochastic process}
\begin{align}
    \HSVvol \notag\\
    \HSVstock \notag \\
    \rho  &= d\Bmsub{v} d\Bmsub{s}  \notag
\end{align}
  
\end{block}


\end{frame}
% -----------------------------------------------------------------------------


% -----------------------------------------------------------------------------
\begin{frame}{MJD: log-return density}

\begin{block}{Impact on the skewness ($\rho$)}
\begin{figure}[ht]
\centering
\input{../figures/skewnessHeston2.tex}
\end{figure}
\end{block}
\end{frame}

\begin{frame}{MJD: log-return density}
\begin{block}{Impact on the kurtosis ($\sigma$)}
\begin{figure}[ht]
\centering
\input{../figures/density.heston.kurtosis2.tex}
\end{figure}

\end{block}
 
\end{frame}
% -----------------------------------------------------------------------------





\subsection{Options pricing method}
% ----------------------------------------------------------------------------- 
\begin{frame}{Heston probabilistic approach}


\begin{align}
  c(t) &= S(t) P_1 - e^{-r(T-t)} K P_2 \notag \\
\intertext{With}
  P_1(x,V,t;\ln{K}) &= \frac{1}{2} + \frac{1}{\pi} \int_0^{\infty} Re \left( \frac{e^{-i\phi\ln{K}} \psi(x,V,t;\phi - i)}{i\phi\psi(x,V,t;-i)} \right) d\phi \notag \\ 
  \intertext{}
  P_2(x,V,t;\ln{K}) &= \frac{1}{2} + \frac{1}{\pi} \int_0^{\infty} Re \left( \frac{e^{-i\phi\ln{K}} \psi(x,V,t;\phi)}{i\phi} \right) d\phi \notag
\end{align}
  


 
\end{frame}
% -----------------------------------------------------------------------------

% -----------------------------------------------------------------------------